### PR TITLE
Feature/admin redesign

### PR DESCRIPTION
**Pull request by jj105**
# Resolves [272](https://github.com/ChildMindInstitute/mindlogger-admin/issues/272), [273](https://github.com/ChildMindInstitute/mindlogger-admin/issues/273)

[572](https://github.com/ChildMindInstitute/mindlogger-admin/issues/572),
[571](https://github.com/ChildMindInstitute/mindlogger-admin/issues/571),
[566](https://github.com/ChildMindInstitute/mindlogger-admin/issues/566),
[565](https://github.com/ChildMindInstitute/mindlogger-admin/issues/565),
[563](https://github.com/ChildMindInstitute/mindlogger-admin/issues/563),
[562](https://github.com/ChildMindInstitute/mindlogger-admin/issues/562),
[561](https://github.com/ChildMindInstitute/mindlogger-admin/issues/561),
[560](https://github.com/ChildMindInstitute/mindlogger-admin/issues/560),
[559](https://github.com/ChildMindInstitute/mindlogger-admin/issues/559)

### CODE REVIEW

**Review by Matchdev120 — APPROVED** [review]

**Comment by jj105** [comment]
Resolves [519](https://github.com/ChildMindInstitute/mindlogger-admin/issues/519), [573](https://github.com/ChildMindInstitute/mindlogger-admin/issues/573)

**Comment by jj105** [comment]
Resolves [429](https://github.com/ChildMindInstitute/mindlogger-admin/issues/429)

**Comment by jj105** [comment]
Resolves [486](https://github.com/ChildMindInstitute/mindlogger-admin/issues/486)

**Comment by jj105** [comment]
Resolves [614](https://github.com/ChildMindInstitute/mindlogger-admin/issues/614)

**Comment by jj105** [comment]
Resolves [612](https://github.com/ChildMindInstitute/mindlogger-admin/issues/612),
[480](https://github.com/ChildMindInstitute/mindlogger-admin/issues/480)

**Comment by jj105** [comment]
Resolves [617](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/617),
[616](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/616)

**Comment by jj105** [comment]
Resolves [577](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/577)

**Comment by jj105** [comment]
Resolves [611](https://github.com/ChildMindInstitute/mindlogger-admin/issues/611), [605](https://github.com/ChildMindInstitute/mindlogger-admin/issues/605), [1405](https://github.com/ChildMindInstitute/mindlogger-app/issues/1405), [606](https://github.com/ChildMindInstitute/mindlogger-admin/issues/606)

**Comment by jj105** [comment]
Resolves [586](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/586)

**Comment by jj105** [comment]
Resolves [1302](https://github.com/childMindInstitute/mindlogger-app/issues/1302)

**Comment by jj105** [comment]
Resolves [1405](https://github.com/childMindInstitute/mindlogger-app/issues/1405)

**Comment by jj105** [comment]
Resolves [619](https://github.com/ChildMindInstitute/mindlogger-admin/issues/619)

**Comment by jj105** [comment]
Resolves [480](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/480), [586](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/586), [636](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/636)

**Comment by jj105** [comment]
Resolves [526](https://github.com/ChildMindInstitute/mindlogger-admin/issues/526), [591](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/591)

**Review by devbtech — APPROVED** [review]

**Pull request merged**
